/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.project.allocation;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileFilter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Sahitha Nelanga
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Home() {
        initComponents();
        
        btn_view.setText("<html><center><b>View Dataset</html>");
        //btn_auto.setText("<html><center><b>Auto Allocate <br />Assignment / Projects</html>");
        btn_sa.setText("<html><center><b>View SA <br />Solution</html>");
        btn_ga.setText("<html><center><b>View GA <br />Solution</html>");
       // btn_search.setText("<html><center><b>Search<br />Invalid Mappings</html>");
        btn_results.setText("<html><center><b>View<br/>Results</html>");
        btn_db.setText("<html><center><b>Load <br />Dataset</html>");
        //txtp_dbpath.setText("database path");
        
        //Screen Sizing
        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //setBounds(0,0,screenSize.width, screenSize.height);
        //setVisible(true);
        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //setBounds(0,0,screenSize.width, screenSize.height-50);
        //pack();
        
        //set default close and thank message
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
//                int close = JOptionPane.showConfirmDialog(null, 
//                        "<html>Thank You for using <b>Automated Project Allocation System - 6Droids</b> </html>",
//                        "Thank You!",JOptionPane.NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(null, "<html>Thank You for using <b>Automated Project Allocation System</b> by <b>6Droids</b></html>",
                        "Thank You!", JOptionPane.INFORMATION_MESSAGE);
                        e.getWindow().dispose();

            }
            
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_view = new javax.swing.JButton();
        btn_db = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtp_dbpath = new javax.swing.JTextPane();
        lbl_dbname = new javax.swing.JLabel();
        lbl_projectname = new javax.swing.JLabel();
        btn_sa = new javax.swing.JButton();
        btn_ga = new javax.swing.JButton();
        btn_results = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_projectname1 = new javax.swing.JLabel();
        lbl_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Project Allocation - Home");
        setMaximumSize(new java.awt.Dimension(1024, 700));
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setPreferredSize(new java.awt.Dimension(1024, 700));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setName("panel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btn_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/project/allocation/icons/student.png"))); // NOI18N
        btn_view.setText("View Students");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        btn_db.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/project/allocation/icons/upload.png"))); // NOI18N
        btn_db.setText("Load Database");
        btn_db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dbActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtp_dbpath);

        lbl_dbname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(lbl_dbname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(btn_db, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_db)
                        .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_dbname, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        lbl_projectname.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        lbl_projectname.setText("Automated Project Allocation System");

        btn_sa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/project/allocation/icons/sa.png"))); // NOI18N
        btn_sa.setText("View SA Solution");
        btn_sa.setMaximumSize(new java.awt.Dimension(163, 61));
        btn_sa.setMinimumSize(new java.awt.Dimension(163, 61));
        btn_sa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saActionPerformed(evt);
            }
        });

        btn_ga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/project/allocation/icons/ga.png"))); // NOI18N
        btn_ga.setText("View GA Solutions");
        btn_ga.setMaximumSize(new java.awt.Dimension(169, 61));
        btn_ga.setMinimumSize(new java.awt.Dimension(169, 61));
        btn_ga.setPreferredSize(new java.awt.Dimension(169, 61));
        btn_ga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gaActionPerformed(evt);
            }
        });

        btn_results.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/project/allocation/icons/results.png"))); // NOI18N
        btn_results.setText("View Results");
        btn_results.setMaximumSize(new java.awt.Dimension(145, 61));
        btn_results.setMinimumSize(new java.awt.Dimension(145, 61));
        btn_results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultsActionPerformed(evt);
            }
        });

        lbl_projectname1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_projectname1.setText("Stochastic Technique Solutions");

        lbl_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/project/allocation/icons/info.png"))); // NOI18N
        lbl_info.setToolTipText("info");
        lbl_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_infoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_projectname)
                .addGap(233, 233, 233))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_sa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_projectname1)
                                .addGap(343, 343, 343))
                            .addComponent(lbl_info)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_ga, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197)
                                .addComponent(btn_results, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_projectname)
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_projectname1)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ga, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_results, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lbl_info))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("frame1");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saActionPerformed
        Results results = new Results(this);
        results.setVisible(true);
        results.lbl_title.setText("<html><b>Results of SA Solution</html>");
        this.setVisible(false);
    }//GEN-LAST:event_btn_saActionPerformed

    private void btn_gaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gaActionPerformed
        Results results = new Results(this);
        results.setVisible(true);
        results.lbl_title.setText("<html><center><b>Results of GA Solution</html>");
        this.setVisible(false);
    }//GEN-LAST:event_btn_gaActionPerformed

    private void btn_dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dbActionPerformed

        try {
        JFileChooser chooser = new JFileChooser();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TSV Dataset Files", "tsv", "TSV");
        chooser.setFileFilter(filter);
        
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        
        String dbpath = file.getAbsolutePath();
        String dbname = file.getName();
        txtp_dbpath.setText(dbpath);
        lbl_dbname.setText("<html><b>("+dbname+"<html><b>)");
        } catch (NullPointerException e) {
            //e.printStackTrace();
            if (txtp_dbpath.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please select a database file to continue!");
            }
            
        }
        
    }//GEN-LAST:event_btn_dbActionPerformed

    private void lbl_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_infoMouseClicked
        JOptionPane.showMessageDialog(null, "<html><left><b>14208971 Tharkana D Kodagoda<br/>"
                                                            + "<left>14208893 Sahitha Nelanga H De Silva<br/>"
                                                            + "<left>14208910 H W Srimal Priyanga Fonseka<br/>"
                                                            + "<left>14209059 Dilina Namal Weerasinghe<br/>"
                                                            + "<left>14209074 P W Poorni Yasodara<br/>"
                                                            + "<left>14209759 Kavindu Yudeesha Lakshan Narathota</html>");
    }//GEN-LAST:event_lbl_infoMouseClicked

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        Data_View data_View = new Data_View(this);
        data_View.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_resultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultsActionPerformed
        All_Results all_Results = new All_Results(this);
        all_Results.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_resultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_db;
    private javax.swing.JButton btn_ga;
    private javax.swing.JButton btn_results;
    private javax.swing.JButton btn_sa;
    private javax.swing.JButton btn_view;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_dbname;
    private javax.swing.JLabel lbl_info;
    private javax.swing.JLabel lbl_projectname;
    private javax.swing.JLabel lbl_projectname1;
    private javax.swing.JTextPane txtp_dbpath;
    // End of variables declaration//GEN-END:variables
}
